config/routes.rb
Rails.application.routes.draw do
  resources :blog_comments
  resources :blog_comments
  resources :blog_posts
  get '/' => 'blog_posts#index'
  get '/blog' => 'blog_posts#index' 
  get '/blog/comments' => 'blog_comments#index'
 get '/home' => 'static_pages#home'

  get '/about' => 'static_pages#about'

  get '/contact' => 'static_pages#contact'
  get '/gallery' => 'arts#index'
  resources :arts

end

app/models/art.rb
class Art < ActiveRecord::Base
  has_attached_file :image
  validates_presence_of :image
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
  belongs_to :blog_post
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	has_many :blog_comment
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: [:show, :edit, :update, :destroy]

  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:name, :year, :description, :image)
    end
end

app/controllers/blog_comment_controller.rb
class BlogCommentController < ApplicationController
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController
  before_action :set_blog_comment, only: [:show, :edit, :update, :destroy]

  # GET /blog_comments
  # GET /blog_comments.json
  def index
    @blog_comments = BlogComment.all
  end

  # GET /blog_comments/1
  # GET /blog_comments/1.json
  def show
  end

  # GET /blog_comments/new
  def new
    @blog_comment = BlogComment.new
  end

  # GET /blog_comments/1/edit
  def edit
  end

  # POST /blog_comments
  # POST /blog_comments.json
  def create
    @blog_comment = BlogComment.new(blog_comment_params)

    respond_to do |format|
      if @blog_comment.save
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully created.' }
        format.json { render :show, status: :created, location: @blog_comment }
      else
        format.html { render :new }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_comments/1
  # PATCH/PUT /blog_comments/1.json
  def update
    respond_to do |format|
      if @blog_comment.update(blog_comment_params)
        format.html { redirect_to @blog_comment, notice: 'Blog comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_comment }
      else
        format.html { render :edit }
        format.json { render json: @blog_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_comments/1
  # DELETE /blog_comments/1.json
  def destroy
    @blog_comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_comments_url, notice: 'Blog comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_comment
      @blog_comment = BlogComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_comment_params
      params.require(:blog_comment).permit(:name, :body, :user, :blog_post_id)
    end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all.order("created_at DESC")
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/blog_comment_helper.rb
module BlogCommentHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/arts/_form.html.erb
<%= form_for(@art, :html => { :multipart => true }) do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %> <br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gallery</h1>

  <div>
	<ul class="artlist">
    <% @arts.each do |art| %>
      <li class="artpiece"><div>
        <span> <%= image_tag(art.image.url, height:200, width:300) %> </span> <br />
        <span><strong>Name:</strong> <%= art.name %></span> <br />
        <span><strong>Year:</strong> <%= art.year %></span> <br />
        <span><strong>Description:</strong> <%= art.description %></span> &nbsp;
<p>
        <span><%= link_to 'Show', art %></span>  &nbsp;
        <span><%= link_to 'Edit', edit_art_path(art) %></span>
        <span><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></span> <br />
</p>
</div>
<li>
    <% end %>
  </ul>

<br>

<%= link_to 'New Art', new_art_path %>

app/views/arts/new.html.erb
<h1>New Art</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @art.image.url %>

<p>
  <strong>Name:</strong>
  <%= @art.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @art.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @art.description %>
</p>

<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>

app/views/blog_comments/_form.html.erb
<%= form_for(@blog_comment) do |f| %>
  <% if @blog_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_comment.errors.count, "error") %> prohibited this blog_comment from being saved:</h2>

      <ul>
      <% @blog_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :blog_post_id %><br>
    <%= f.text_field :blog_post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_comments/edit.html.erb
<h1>Editing Blog Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_comment %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>User</th>
      <th>Blog post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_comments.each do |blog_comment| %>
      <tr>
        <td><%= blog_comment.name %></td>
        <td><%= blog_comment.body %></td>
        <td><%= blog_comment.user %></td>
        <td><%= blog_comment.blog_post %></td>
        <td><%= link_to 'Show', blog_comment %></td>
        <td><%= link_to 'Edit', edit_blog_comment_path(blog_comment) %></td>
        <td><%= link_to 'Destroy', blog_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog comment', new_blog_comment_path %>

app/views/blog_comments/new.html.erb
<h1>New Blog Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_comments_path %>

app/views/blog_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog_comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog_comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog_comment.user %>
</p>

<p>
  <strong>Blog post:</strong>
  <%= @blog_comment.blog_post %>
</p>

<%= link_to 'Edit', edit_blog_comment_path(@blog_comment) %> |
<%= link_to 'Back', blog_comments_path %>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Latest Updates</h1>


    <% @blog_posts.each do |blog_post| %>
        <div class="blogbox">

        <div class="blogtitlebox">
        <h2 class = "blogtitle"><%= link_to blog_post.title, blog_post %></h2>
	  <h4 class = "blogcreatedat"><%= blog_post.created_at %></h4>
        </div>
        
        (<span class="edit_entry"><%= link_to 'Edit', edit_blog_post_path(blog_post) %></span>
        <span class="edit_entry"><%= link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></span>)


        <p><%= blog_post.body %></p>
	<hr />
	<div align="center"> Comments </div>
	<div class="commentsbox">
	<div class="comments">
	<% @comments = BlogComment.where(:blog_post_id => blog_post.id) %>
	<% @comments.each do |comment| %>
	<div class="commentpost">
	<h2 class="commenttitle"><%= comment.name %> </h2>
        <hr />
	<h3 class="commentauthor">by: <%= comment.user %> </h3>
	<hr />
        <p><%= comment.body %> </p>
	</div>
        <% end %>
	</div>
	<div class="newcomment" align="center"><%= link_to 'Add comment', new_blog_comment_path %></div>
	</div>
      </div>
    <% end %>
	</div>
</td>
	<td width="60px">

		<%= image_tag ("blogcolumntop.png") %> </br>
		<%= image_tag ("blogcolumn.png") %> </br>
		<%= image_tag ("blogcolumnbottom.png") %>
</td>


<br>

<div class="newblog" align="center"><%= link_to 'New Blog post', new_blog_post_path %></div>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog_post.body %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SevvyArt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="headerbox">
<%= link_to image_tag("logo.png", class: 'headerlogo', alt: 'Ghost Jokes'), 'localhost:3000' %>


<div class="headerlinks">
<%= link_to image_tag('about.png', :onmouseout => "this.src='/images/about.png'", :onmouseover => "this.src='/images/abouthover.gif'"), "/about" %> 

&nbsp; <%= image_tag('cross.png') %> &nbsp;

<%= link_to image_tag('blog.png', :onmouseout => "this.src='/images/blog.png'", :onmouseover => "this.src='/images/bloghover.gif'"), "/blog" %> 

&nbsp; <%= image_tag('cross.png') %> &nbsp;


<%= link_to image_tag('shop.png', :onmouseout => "this.src='/images/shop.png'", :onmouseover => "this.src='/images/shophover.gif'"), "/gallery" %> 


&nbsp; <%= image_tag('cross.png') %> &nbsp;
<%= link_to image_tag('contact.png', :onmouseout => "this.src='/images/contact.png'", :onmouseover => "this.src='/images/contacthover.gif'"), "/contact" %> 

</div>
</div>

<div class="bodybox">
<%= yield %>
</div>

<div class="footer"> All works &copy; 2015 Sevvy Graves, reproduction without permission is strictly prohibited </div>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Sevvy</h1>
Sevvy is a beautiful amazing human being who makes fantastic art, specializing in queer, morbid, and silly works that makes Pax very happy

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Contact Sevvy via Email at Sevvy@SevvyArt.org</p>
<p>On twitter at @SevvyArt</p>
<p>Or on facebook at SevvyArt</p>

app/views/static_pages/home.html.erb
<h1>Welcome to Sevvy's Art Gallery</h1>
<p>Here you will find many beautiful pieces of art created by local seattle queer artist Sevvy Graves. Many of these pieces are for sale and will look great over your fireplace</p>